services:
  - type: web
    name: auto-key-in-merit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: "production" 